### ISSUE TITLE
Question: How to add ionic-native

### ISSUE THREAD

**Issue by fmoessle** [mirkonasato/ionic2-webpack2-starter#4]
Hey,

how exactly do you add native-functionality?

I tried to add some things by installing ionic-native via npm, importing and tried to use them.

Error when using 

> ThreeDeeTouch

> typeError: Cannot read property 'split' of undefined

**Comment by mirkonasato** [comment]
You should be able to install it like any other package, i.e. with  `npm install ionic-native --save`.

Note that Cordova plugins are only available when building and running with Cordova. Perhaps that explains the error you're seeing?

**Comment by fmoessle** [comment]
Just found this [https://github.com/driftyco/ionic-native/issues/992](url).
It seems that this error is caused by ionic-native 2.3.0. I am going to try if an older version works.

**Comment by fmoessle** [comment]
Using ionic-native v2.2.16 solved the issue
